# Generated by Django 6.0.2 on 2026-04-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('this', 'Эта'), ('next', 'Следующая')], default='this', max_length=4)),
                ('edu', models.CharField(choices=[('vo', 'ВО'), ('spo', 'СПО')], default='spo', max_length=3)),
                ('file', models.FileField(upload_to='schedules')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
