# Generated by Django 6.0.2 on 2026-04-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')])),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('patronymic', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.date')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('auditorium', models.CharField(max_length=100)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='schedule.group')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='schedule.lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='schedule.teacher')),
            ],
        ),
    ]
