# Generated by Django 6.0.2 on 2026-05-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_teacher_options_announcement_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_type', models.CharField(max_length=100)),
                ('raw_data', models.JSONField()),
                ('description', models.TextField()),
                ('is_fixed', models.BooleanField(default=False)),
            ],
        ),
    ]
