# Generated by Django 6.0.2 on 2026-05-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb_admin', '0001_initial'),
        ('schedule', '0005_alter_date_weekday_delete_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('auditorium', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='schedule.date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lessons', to='schedule.group')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='ieb_admin.schedule')),
                ('teachers', models.ManyToManyField(blank=True, related_name='lessons', to='schedule.teacher')),
            ],
            options={
                'ordering': ['date', 'order'],
            },
        ),
    ]
