# Generated by Django 6.0.2 on 2026-05-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lessons', to='schedule.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.CharField(choices=[('SPO', 'Среднее профессиональное образование (СПО)'), ('VO', 'Высшее образование (ВО)')], default='SPO', max_length=3),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='schedule.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='search_name',
            field=models.CharField(default='Артюхин В.В.', help_text='Как преподаватель записан в Excel (например: Артюхин А.С.)', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='schedule.date'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='profession',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='auditorium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='schedule.date'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lessons', to='schedule.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.DeleteModel(
            name='TeacherLesson',
        ),
    ]
