# Generated by Django 6.0.2 on 2026-05-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_scheduleerror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'order']},
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
