# Generated by Django 6.0.2 on 2026-05-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleerror',
            name='error_type',
        ),
        migrations.RemoveField(
            model_name='scheduleerror',
            name='is_fixed',
        ),
        migrations.AlterField(
            model_name='scheduleerror',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
