# Generated by Django 5.2.12 on 2026-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_date_id_alter_group_id_alter_lesson_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleerror',
            name='raw_data',
            field=models.JSONField(),
        ),
    ]
