# Generated by Django 5.2.12 on 2026-05-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb_admin', '0002_alter_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
