# Generated by Django 5.2.12 on 2026-05-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb_admin', '0003_alter_schedule_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('edu', 'week'), name='unique_schedule_edu_week'),
        ),
    ]
