name: Deploy Django with Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Connect to VM and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Прерывать выполнение скрипта, если любая из команд завершится ошибкой
          set -e
          
          # 1. Переходим в правильную папку по АБСОЛЮТНОМУ пути
          cd /opt/ineb/ieb_schedule
          
          # 2. Подтягиваем изменения из GitHub
          git pull origin main
          
          # 3. Принудительно тушим старые контейнеры, собираем и поднимаем новые
          docker compose down
          docker compose up --build -d web
          
          # 4. Очищаем старые неиспользуемые слои докера
          docker image prune -f